### ISSUE TITLE
Changeable Keyboard Positions

### ISSUE THREAD

**Issue by Tronzolor** [ClaytonDoesThings/SymbolTranslator#8]
I think it'd be awesome if there was an easy way to change the location for the keyboards. I've realized this possible improvement specifically on this keyboard/translator -(https://claytonxyz.herokuapp.com/w/software/symbol-translator/web)

What I mean by changing location is the ability to change where each symbol is on the keyboard without having to change the font files (For example, in English to be able to switch the letters A and L, or in this case to change where the symbols are located on the keyboard). My reason for why this would be helpful is that when it comes to symbol translating, it would be extremely helpful to have similar symbols next to each other. In the link I typed above, there's an Alien Text you can decode, but it's hard to find which symbol you're looking for because of how spaced out each one is.

It would be way easier if, in this instance, that you could move the symbols for PIJD next to each other due to how similar they look, or possibly ZWR. I think this could be beneficial for different reasons too, such as if you wanted to put letters and numbers in alphabetical order, or if you wanted to kinda make it qwerty (or qwertz). Just something I think would be useful.

**Comment by clay53** [comment]
This would also complete issue #6. Adding onto this, the user will also be able to specify which keyboard layout/positions would be used for each font.

**Comment by clay53** [comment]
Also includes issue #5
